---
settings:
  name: VSC, VASA Provider, and SRA 9.7
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: VSC, VASA Provider, and SRA docs
      url: /index.html
    - title: Release notes
      url: /release-notes.html
    - title: Quick start
      url: /qsg.html
    - section: deploy
    - section: manage
    - title: Legal notices
      url: /legal-notices.html

