---
permalink: deploy/concept_configuring_high_availability_for_virtual_appliance_for_vsc_vasa_provider_and_sra.html
sidebar: sidebar
keywords: 
summary: 'The virtual appliance for Virtual Storage Console \(VSC\), VASA Provider, and Storage Replication Adapter \(SRA\) supports a \(HA\) configuration to help provide uninterrupted functionality of VSC, VASA Provider, and SRA during failure.'
---
= Configuring high availability for the virtual appliance for VSC, VASA Provider, and SRA
:icons: font
:imagesdir: ../media/

[.lead]
The virtual appliance for Virtual Storage Console (VSC), VASA Provider, and Storage Replication Adapter (SRA) supports a (HA) configuration to help provide uninterrupted functionality of VSC, VASA Provider, and SRA during failure.

The virtual appliance for VSC, VASA Provider, and SRA relies on the VMware vSphere (HA) feature and vSphere fault tolerance (FT) feature to provide . (HA) solution provides for rapid recovery from outages caused by:

* Host failure
* Network failure
* Virtual machine failure (Guest OS failure)
* Application (VSC, VASA Provider, and SRA) crash

No additional configuration is required on the virtual appliance to provide . Only the vCenter Server and ESXi hosts must be configured with the VMware vSphere HA feature or the vSphere FT feature based on their requirements. Both HA and FT require clustered hosts together with shared storage. FT has additional requirements and limitations.

In addition to the VMware vSphere HA solution and vSphere FT solution, the virtual appliance also helps keep the VSC, VASA Provider, and SRA services running at all times. The virtual appliance watchdog process periodically monitors all three services, and restarts them automatically when any kind of failure is detected. This helps to prevent application failures.

[NOTE]
====
vCenter HA is not supported by virtual appliance for VSC, VASA Provider, and SRA.
====
