---
permalink: deploy/reference-configuring-guest-operating-system-scripts.html
sidebar: sidebar
keywords: guest, operating, system, configuring, scripts,
summary: "The ISO images of the guest operating system (OS) scripts are mounted on the Virtual Storage Console for VMware vSphere server. To use the guest OS scripts to set the storage timeouts for virtual machines, you must mount the scripts from the vSphere Client."
---
= Configuring guest operating system scripts
:icons: font
:imagesdir: ../media/

[.lead]
The ISO images of the guest operating system (OS) scripts are mounted on the Virtual Storage Console for VMware vSphere server. To use the guest OS scripts to set the storage timeouts for virtual machines, you must mount the scripts from the vSphere Client.

[cols="1a,1a,1a" options="header"]
|===
| Operating System Type| 60-second timeout settings| 190-second timeout settings
a|
Linux
a|
`https://<appliance_ip>:8143/vsc/public/writable/linux_gos_timeout-install.iso`
a|
`https://<appliance_ip>:8143/vsc/public/writable/linux_gos_timeout_190-install.iso`
a|
Windows
a|
`https://<appliance_ip>:8143/vsc/public/writable/windows_gos_timeout.iso`
a|
`https://<appliance_ip>:8143/vsc/public/writable/windows_gos_timeout_190.iso`
a|
Solaris
a|
`https://<appliance_ip>:8143/vsc/public/writable/solaris_gos_timeout-install.iso`
a|
`https://<appliance_ip>:8143/vsc/public/writable/solaris_gos_timeout_190-install.iso`
|===
You should install the script from the copy of the VSC instance that is registered to the vCenter Server that manages the virtual machine. If your environment includes multiple vCenter Servers, you should select the server that contains the virtual machine for which you want to set the storage timeout values.

You should log in to the virtual machine, and then run the script to set the storage timeout values.
