---
permalink: deploy/reference-unable-to-install-sra-plug-in-due-to-winhttp-proxy-settings.html
sidebar: sidebar
keywords: unable, to, install, the, sra, plug-in,
summary: "Unable to install the SRA plug-in"
---
= Unable to install the SRA plug-in
:icons: font
:imagesdir: ../media/

== Issue

During the installation of the Storage Replication Adapter (SRA) plug-in, the system stops at the server IP address and password screen with the following error message: "`The credentials you entered are not valid. Please enter a valid hostname and password.`"

== Cause

The error might occur due to one of the following reasons:

* You entered incorrect administrator credentials.
* The WinHTTP proxy settings are incorrect.

== Corrective action

* Verify your administrator credentials.
* The knowledgebase article has more information about resolving issues with WinHTTP proxy settings.
+
https://kb.netapp.com/app/answers/answer_view/a_id/1005074[NetApp Knowledgebase Answer 1005074: Installing of SRA 4.0P1 client plugin (netapp_sra_4.0P1_ontap_64bit.msi) hangs at the server IP and password screen^]
