---
permalink: deploy/reference-configure-storage-replication-adapter-for-highly-scaled-environment.html
sidebar: sidebar
keywords: configuration, storage, replication, adapter, highly, scaled, environment,
summary: "You must configure the storage timeout intervals per the recommended settings for Storage Replication Adapter (SRA) to perform optimally in highly scaled environments."
---
= Configuration of Storage Replication Adapter for highly scaled environment
:icons: font
:imagesdir: ../media/

[.lead]
You must configure the storage timeout intervals per the recommended settings for Storage Replication Adapter (SRA) to perform optimally in highly scaled environments.

== Storage Provider settings

* You must increase the value of the `StorageProvider.resignatureTimeout` setting from 900 seconds to 12000 seconds.
* You must enable the `StorageProvider.autoResignatureMode` option.

See VMware documentation for more information on modifying Storage Provider settings.

https://docs.vmware.com/en/Site-Recovery-Manager/6.5/com.vmware.srm.admin.doc/GUID-E4060824-E3C2-4869-BC39-76E88E2FF9A0.html[VMware vSphere Documentation: Change Storage Provider Settings^]

== Storage settings

You must set the value of the `storage.commandTimeout` timeout interval for highly scaled environments to 12,000 seconds.

[NOTE]
====
The timeout interval specified is the maximum value. You do not need to wait for the maximum timeout to be reached. Most commands finish within the set maximum timeout interval.
====

https://kb.netapp.com/app/answers/answer_view/a_id/1001111[NetApp Knowledgebase Answer 1001111: NetApp Storage Replication Adapter 4.0/7.X for ONTAP Sizing Guide^]

VMware documentation on modifying SAN Provider settings has more information.

https://docs.vmware.com/en/Site-Recovery-Manager/6.5/com.vmware.srm.admin.doc/GUID-711FD223-50DB-414C-A2A7-3BEB8FAFDBD9.html[Vmware Site Recovery Manager Documentation: Change Storage Settings^]
