---
permalink: deploy/reference-considerations-for-deploying-virtual-appliance-for-vsc-vasa-provider-and-sra.html
sidebar: sidebar
keywords: considerations, requirements, deploying, virtual, appliance, vsc, vasa, provider, sra,
summary: "Before you deploy the virtual appliance for Virtual Storage Console (VSC), VASA Provider, and Storage Replication Adapter (SRA), it is good practice to plan your deployment and decide how you want to configure VSC, VASA Provider, and SRA in your environment."
---
= Considerations and requirements for deploying the virtual appliance for VSC, VASA Provider, and SRA
:icons: font
:imagesdir: ../media/

[.lead]
Before you deploy the virtual appliance for Virtual Storage Console (VSC), VASA Provider, and Storage Replication Adapter (SRA), it is good practice to plan your deployment and decide how you want to configure VSC, VASA Provider, and SRA in your environment.

The following table presents an overview of what you should consider before you deploy the virtual appliance for VSC, VASA Provider, and SRA.

[cols="1a,1a" options="header"]
|===
| Considerations| Description
a|
First-time deployment of the virtual appliance for VSC, VASA Provider, and SRA
a|
The deployment of the virtual appliance for VSC, VASA Provider, and SRA automatically installs the VSC features. link:concept-deploy-or-upgrade-ontap-tools.html[Deploying or upgrading VSC, VASA Provider, and SRA^]

link:concept-installation-workflow-for-new-users.html[Deployment workflow for new users of VSC, VASA Provider, and SRA virtual appliance^]

a|
Upgrading from an existing deployment of VSC
a|
The upgrade procedure from an existing deployment of VSC to the virtual appliance for VSC, VASA Provider, and SRA depends on the version of VSC, and whether you have deployed VSC, VASA Provider, and SRA. The deployment workflows and upgrade section has more information. link:concept-installation-workflow-for-existing-users-of-vsc.html[Deployment workflow for existing users of VSC, VASA Provider, and SRA^]

Best practices before an upgrade:

* You should record information about the storage systems that are being used and their credentials.
+
After the upgrade, you should verify that all of the storage systems were automatically discovered and that they have the correct credentials.

* If you modified any of the standard VSC roles, you should copy those roles to save your changes.
+
VSC overwrites the standard roles with the current defaults each time you restart the VSC service.

a|
Regenerating an SSL certificate for VSC
a|
The SSL certificate is automatically generated when you deploy the virtual appliance for VSC, VASA Provider, and SRA. You might have to regenerate the SSL certificate to create a site-specific certificate. link:task-regenerating-an-ssl-certificate-for-vsc.html[Regenerating an SSL certificate for^]

a|
Setting ESXi server values
a|
Although most of your ESXi server values are set by default, it is a good practice to check the values. These values are based on internal testing. Depending on your environment, you might have to change some of the values to improve performance.

* link:task-configuring-esx-server-multipathing-and-timeout-settings.html[Configuring ESXi server multipathing and timeout settings^]
* link:reference-esx-host-values-set-by-vsc-for-vmware-vsphere.html[ESXi host values set using Virtual Storage Console for VMware vSphere^]

a|
Guest operating system timeout values
a|
The guest operating system (guest OS) timeout scripts set the SCSI I/O timeout values for supported Linux, Solaris, and Windows guest operating systems to provide correct failover behavior.
|===

The following table presents an overview of what you require to configure the virtual appliance for VSC, VASA Provider, and SRA.

[cols="1a,1a" options="header"]
|===
| Considerations| Description
a|
Requirements of role-based access control (RBAC)
a|
VSC supports both vCenter Server RBAC and ONTAP RBAC. The account used to register VSC to vCenter Server (using `_https_://<appliance_ip>:8143/Register.html`) must be a vCenter Server administrator (assigned to the vCenter Server administrator or administrator role). If you plan to run VSC as an administrator, you must have all of the required permissions and privileges for all of the tasks.

If your company requires that you restrict access to vSphere objects, you can create and assign standard VSC roles to users to meet the vCenter Server requirements.

You can create the recommended ONTAP roles by using ONTAP System Manager using the JSON file provided with the virtual appliance for VSC, VASA Provider, and SRA.

If a user attempts to perform a task without the correct privileges and permissions, the task options are grayed out.

* link:concept-standard-roles-packaged-with-virtual-appliance-for-vsc-vp-and-sra.html[Standard roles packaged with the virtual appliance for VSC, VASA Provider, and SRA^]
* link:concept-recommended-ontap-roles-when-using-vsc-for-vmware-vsphere.html[Recommended ONTAP roles when using VSC for VMware vSphere^]

a|
ONTAP version
a|
Your storage systems must be running ONTAP 9.1, 9.3, 9.5, 9.6, or 9.7.
a|
Storage capability profiles
a|
To use storage capability profiles or to set up alarms, you must enable VASA Provider for ONTAP. After you enable VASA Provider, you can configure VMware Virtual Volumes (vVols) datastores, and you can create and manage storage capability profiles and alarms.

The alarms warn you when a volume or an aggregate is at nearly full capacity or when a datastore is no longer in compliance with the associated storage capability profile.

|===
