---
permalink: deploy/reference_sra_adapter_installation_fails_with_script_error.html
sidebar: sidebar
keywords: Storage Replication Adapter
summary: ''
---
= SRA installation fails with script error
:icons: font
:imagesdir: ../media/

== Issue

Storage Replication Adapter (SRA) installation on Windows 2008 R2 fails with an invalid credentials error.

== Cause

The error might occur because of different versions of Transport Layer Security (TLS) being enabled on the virtual appliance for VSC, VASA Provider, and SRA and Windows 2008 R2.

== Corrective action

If you are trying to install SRA on Windows 2008 R2, then you must enable TLSv1.0 for the virtual appliance for VSC, VASA Provider, and SRA using the following steps in the maintenance console:

. Login to the maintenance console using the "`maint`" user credentials.
. From the main menu, select *1* for the Application configuration menu.
. Enter *13* in the Application configuration menu to select Enable TLS Protocolfrom the Application Configuration menu.
. Select *TLSv1* in the TLS protocol list.
+
VSC and VASA Provider services are restarted and TLSv1.0 is enabled.

You can also enable TLSv1.2 on Windows 2008 R2.
