---
permalink: deploy/task-configure-vasa-provider-to-use-ssh-for-remote-diag-access.html
sidebar: sidebar
keywords: configuring, virtual, appliance, vsc, vasa, provider, sra, use, ssh, for, remote, diag, access,
summary: "You can configure virtual appliance for Virtual Storage Console (VSC), VASA Provider, and Storage Replication Adapter (SRA) to enable SSH access for the diag user."
---
= Configure the virtual appliance for VSC, VASA Provider, and SRA to use SSH for remote diag access
:icons: font
:imagesdir: ../media/

[.lead]
You can configure virtual appliance for Virtual Storage Console (VSC), VASA Provider, and Storage Replication Adapter (SRA) to enable SSH access for the diag user.

.Before you begin

The VASA Provider extension must be enabled for your vCenter Server instance.

.About this task

Using SSH to access the diag user has the following limitations:

* You are allowed only one login per activation of SSH.
* SSH access to the diag user is disabled when one of the following happens:
 ** The time expires.
+
The login session remains valid only until midnight the next day.

 ** You log in as a diag user again using SSH.

.Steps

. From the vCenter Server, open a console to VASA Provider.
. Log in as the maint user.
. Enter `4` to select *Support and Diagnostics*.
. Enter `3` to select *Enable remote diagnostics access*.
. Enter `y` in the *Confirmation* dialog box to enable remote diagnostic access.
. Enter a password for remote diagnostic access.
