---
permalink: deploy/task-deploy-ontap-tools.html
sidebar: sidebar
keywords: deploying, the, virtual, appliance, for vsc, vasa, provider, and sra,
summary: "You should deploy the virtual appliance for Virtual Storage Console (VSC), VASA Provider, and Storage Replication Adapter (SRA) in your environment, and specify the required parameters, to be able to use the appliance."
---
= Deploying the virtual appliance for VSC, VASA Provider, and SRA
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
You should deploy the virtual appliance for Virtual Storage Console (VSC), VASA Provider, and Storage Replication Adapter (SRA) in your environment, and specify the required parameters, to be able to use the appliance.

.Before you begin

* You must be running a supported release of vCenter Server.
+
[NOTE]
====
The virtual appliance for VSC, VASA Provider, and SRA can be registered either with a Windows deployment of vCenter Server or a VMware vCenter Server Virtual Appliance (vCSA) deployment.
====
+
https://mysupport.netapp.com/matrix/imt.jsp?components=97563;&solution=56&isHWU&src=IMT[Interoperability Matrix Tool: VSC 9.7^]

* You must have configured and set up your vCenter Server environment.
* You must have set up an ESXi host for your virtual machine.
* You must have downloaded the `.ova` file.
* You must have the administrator login credentials for your vCenter Server instance.
* You must have logged out of and closed all of the browser sessions of vSphere Client, and deleted the browser cache to avoid any browser cache issue during the deployment of the virtual appliance for VSC, VASA Provider, and SRA.
+
xref:task-cleaning-the-vsphere-cached-downloaded-plug-in-packages.adoc[Cleaning the vSphere cached downloaded plug-in packages]

* You must have enabled Internet Control Message Protocol (ICMP ).
+
If ICMP is disabled, then the initial configuration of the virtual appliance for VSC, VASA Provider, and SRA fails, and VSC cannot start the VSC and VASA Provider services after deployment. You must manually enable the VSC and VASA Provider services after deployment.

.About this task

If you are deploying a fresh installation of the virtual appliance for VSC, VASA Provider, and SRA, then VASA Provider is enabled by default. But in case of an upgrade from an earlier release of the virtual appliance, the state of VASA Provider is retained and you might need to enable VASA Provider manually.

link:task-enable-vasa-provider-for-configuring-virtual-datastores.html[Enabling VASA Provider for configuring virtual datastores]

.Steps

. Log in to the vSphere Client.
. Select menu:Home[Host & Clusters].
. Right-click the required datacenter, and then click *Deploy OVA template*.
. Select the applicable method to provide the deployment file for VSC, VASA Provider, and SRA, and then click *Next*.
+
[cols="1a,1a" options="header"]
|===
| Location| Action
a|
URL
a|
Provide the URL for the `.ova` file for the virtual appliance for VSC, VASA Provider, and SRA.
a|
Folder
a|
Select the `.ova` file for the virtual appliance for VSC, VASA Provider, and SRA from the saved location.
|===

. Enter the details to customize the deployment wizard.
+
See link:reference-deploment-customization-requirements.html[Deployment customization considerations] for complete details.

. Review the configuration data, and then click *Next* to finish deployment.
+
As you wait for deployment to finish, you can view the progress of the deployment from the *Tasks* tab.

. Power on the virtual appliance virtual machine, and then open a console of the virtual machine running the virtual appliance.
. Verify that VSC, VASA Provider, and SRA services are running after the deployment is completed.
. If the virtual appliance for VSC, VASA Provider, and SRA is not registered with any vCenter Server, use `+https://appliance_ip:8143/Register.html+` to register the VSC instance.
. Log out and re-log in to the vSphere Client to view the deployed virtual appliance for VSC, VASA Provider, and SRA.
+
It might take a few minutes for the plug-in to be updated in the vSphere Client.
+
[NOTE]
====
If you cannot view the plug-in even after logging in, you must clean the vSphere Client cache.    xref:task-cleaning-the-vsphere-cached-downloaded-plug-in-packages.adoc[Cleaning the vSphere cached downloaded plug-in packages]
====

.After you finish
++ ++
[NOTE]
====
If you are using ONTAP 9.6 or earlier, then to view the vVol dashboard, you must download and install . But for ONTAP 9.7 you do not require to be registered with VASA Provider.
====

xref:task-registering-oncommand-api-services-with-the-virtual-appliance-for-vsc-vasa-provider-and-sra.adoc[Registering with the virtual appliance for VSC, VASA Provider, and SRA]
