---
permalink: deploy/task-upgrading-storage-replication-adapter.html
sidebar: sidebar
keywords: SRA,upgrade
summary: 'After upgrading your virtual appliance for VSC, VASA Provider, and SRA or deploying the latest version of the virtual appliance, you have to upgrade your Storage Replication Adapter \(SRA\).'
---
= Upgrading Storage Replication Adapter
:icons: font
:imagesdir: ../media/

[.lead]
After upgrading your virtual appliance for VSC, VASA Provider, and SRA or deploying the latest version of the virtual appliance, you have to upgrade your Storage Replication Adapter (SRA).

== Steps

. You must upgrade to the latest adapter using one of the following procedures based on your adapter:
+
|===
    a|
*For...*
a|
Perform the following...
a|
*Windows*
a|

 .. Log in to the SRM Windows Server.
 .. Uninstall existing SRA _.msi_ installer from SRM Server.
 .. Change the system path to `C:\Program Files\VMware\VMware vCenter Site Recovery Manager\external\perl\c\bin`
 .. Double-click on the _.msi_ installer you downloaded from NetApp support site, and follow on-screen instructions.
 .. Enter the IP address and password of your deployed virtual appliance for VSC, VASA Provider, and SRA.

a|
*Appliance based adapter*
a|

 .. Log in to the SRM Appliance Managementpage.
 .. Click *Storage Replication Adapter*, and click *Delete* to remove the existing SRA.
 .. Click *New Adapter* > *Browse*.
 .. Click to select the latest SRA tarball file that you downloaded from NetApp support site, and then click *Install*.
 .. Configure SRA on the SRM Appliance.
+
xref:task-configuring-sra-on-srm-appliance.adoc[Configuring SRA on the SRM Appliance]

+
|===
