---
permalink: deploy/task-installing-the-nfs-vaai-plug-in.html
sidebar: sidebar
keywords: installing, the, nfs, vaai, plug-in,
summary: "You can install the NFS Plug-in for VMware vStorage APIs for Array Integration (VAAI) using the GUI of the virtual appliance for Virtual Storage Console (VSC), VASA Provider, and Storage Replication Adapter (SRA)."
---
= Installing the NFS VAAI plug-in
:icons: font
:imagesdir: ../media/

[.lead]
You can install the NFS Plug-in for VMware vStorage APIs for Array Integration (VAAI) using the GUI of the virtual appliance for Virtual Storage Console (VSC), VASA Provider, and Storage Replication Adapter (SRA).

.Before you begin

* You must have downloaded the installation package for the NFS Plug-in for VAAI (`.vib`) from .
+
https://mysupport.netapp.com/site/[NetApp Support^]

* You must have installed ESXi host 6.5 or later and ONTAP 9.1 or later.
* You must have powered on the ESXi host and mounted an NFS datastore.
* You must have set the values of the `DataMover.HardwareAcceleratedMove`, `DataMover.HardwareAcceleratedInit`, and `VMFS3.HardwareAcceleratedLocking` host settings to "`1`".
+
These values are set automatically on the ESXi host when the *Recommended Settings* dialog box is updated.

* You must have enabled the vstorage option on the by using the `vserver nfs modify -vserver vserver_name -vstorage enabled` command.

.Steps

. Rename the `.vib` file that you downloaded from to `NetAppNasPlugin.vib` to match the predefined name that VSC uses.
. Click *Settings* in the VSC home page.
. Click *NFS VAAI Tools* tab.
. Click *Change* in the *Existing version* section.
. Browse and select the renamed `.vib` file, and then click *Upload* to upload the file to the virtual appliance.
. In the *Install on ESXi Hosts* section, select the ESXi host on which you want to install the NFS VAAI plug-in, and then click *Install*.
+
You should follow the on-screen instructions to complete the installation. You can monitor the installation progress in the Tasks section of vSphere Web Client.

. Reboot the ESXi host after the installation finishes.
+
When you reboot the ESXi host, VSC automatically detects the NFS VAAI plug-in. You do not have to perform additional steps to enable the plug-in.
