---
permalink: manage/concept-datastore-reports.html
sidebar: sidebar
keywords: Datastore Reports
summary: 'The datastore reports provide detailed information about traditional datastores and the virtual machines that are created on these datastores.'
---
= Datastore Reports
:icons: font
:imagesdir: ../media/

[.lead]
The datastore reports provide detailed information about traditional datastores and the virtual machines that are created on these datastores.

The traditional dashboard enables you to review and identify potential issues with the datastores and virtual machines in your vCenter Server. You can view, sort, and export reports. The data for the traditional datastores and virtual machines report is provided by the vCenter Server.

The datastore provides the following pre-defined reports:

* Datastore Report
* Virtual Machine Report
* *Datastore Report*
+
The Datastore Report menu provides information on the following parameters for datastores:

 ** Name of the datastore
 ** Type of datastore: NFS or VMFS
 ** Free space
 ** Used space
 ** Total space
 ** Percentage of space utilized
 ** Percentage of space available
 ** IOPS
+
The report displays the IOPS for the datastore.

 ** Latency
+
The report displays the latency information for the datastore.

+
You can also verify the time at which the report was generated. The Datastore Report menu enables you to organize the report as per your requirement, and then export the organized report using the *Export to CSV* button. The datastore names in the report are links that navigate to the Monitor tab of the selected datastore, where you can view the datastore performance metrics.

* *Virtual Machine Report*
+
The Virtual Machine Report menu provides the following performance metrics for all the virtual machines that use datastores provisioned by VSC for a selected vCenter Server:

 ** Name of the virtual machine
 ** Committed capacity
+
The report displays the value for the committed capacity for a virtual machine.

 ** Uptime
+
The report displays the time for which the virtual machine is powered on and is available on an ESXi host.

 ** Latency
+
The report displays the latency for virtual machines across all datastores associated with the virtual machines.

 ** Power state
+
The report displays whether the virtual machine is powered on or powered off.

 ** Host
+
The report displays the host systems on which the virtual machine is available.

Each virtual machine name in the report is a link to the Monitor tab of the selected virtual machine. You can sort the virtual machine report as per your requirement and export the report in a `.CSV` file, and save the report on your local system. The timestamp of the report is also appended to the saved report.
