---
permalink: manage/concept_what_storage_capabilities_are.html
sidebar: sidebar
keywords: storage capability profiles
summary: 'A storage capability is a set of storage system attributes that identifies a specific level of storage performance, storage efficiency, and other capabilities such as encryption for the storage object that is associated with the storage capability.'
---
= What storage capabilities are
:icons: font
:imagesdir: ../media/

[.lead]
A storage capability is a set of storage system attributes that identifies a specific level of storage performance, storage efficiency, and other capabilities such as encryption for the storage object that is associated with the storage capability.

For traditional datastores, you can use a storage capability profile to create datastores consistently with common attributes, and assign QoS policy to them. During provisioning VSC displays clusters, SVMs, and aggregates that match the storage capability profile. You can generate a storage capability profile from existing traditional datastores by using the *GLOBAL AUTO-GENERATE PROFILES* option from the Storage Mapping menu. After the profile is created, you can use VSC to monitor the compliance of datastores with the profile.

When used with VVol datastores, the provisioning wizard can use multiple storage capability profiles to create different FlexVol volumes in the datastore. You can use the VM storage policy to automatically create VVols for a virtual machine in appropriate FlexVol volumes as defined. For example, you can create profiles for common storage classes (such as for performance limits and other capabilities like encryption or FabricPool). You can later create VM storage policies in vCenter Server representing business classes of virtual machines and link these to the appropriate storage capability profile by name (for example Production, Test, HR).

When used with VVols, the storage capability profile is also used to set the storage performance for the individual virtual machine and place it on the FlexVol volume in the vVol datastore that best satisfies the performance requirement. You can specify QoS policy with minimum and/or maximum IOPS for performance. You can use the default policies when you initially provision a virtual machine, or change your VM storage policy later if your business requirements change.

The vCenter Server then associates the storage capability of a LUN or volume with the datastore that is provisioned on that LUN or volume. This enables you to provision a virtual machine in a datastore that matches the storage profile of the virtual machine and to ensure that all of the datastores in a datastore cluster have the same storage service levels.

With the virtual appliance for Virtual Storage Console (VSC), VASA Provider, and Storage Replication Adapter (SRA), you can configure every virtual volume (VVol) datastore with a new storage capability profile that supports the provisioning of virtual machines with varying IOPS requirements on the same vVol datastore. While executing the VM provisioning workflow with IOPS requirement, all of the VVol datastores are listed in the compatible datastore list.

[NOTE]
====
When you try to provision or modify virtual machines for vCenter Server earlier than 6.5, only the vVol datastores that contain storage capability profiles with performance set to "`MAX_IOPS`" are listed in the compatible datastore list. The remaining vVol datastores are listed in the incompatible datastore list. You can ignore this classification and select any vVol datastore from the incompatible datastore list to provision or modify the virtual machine.
====
