---
permalink: manage/reference-vm-provisioning-fails-with-undefined-error.html
sidebar: sidebar
keywords: virtual, machine, provisioning, fails, with, an, undefined, error,
summary: "Virtual machine provisioning operations such as Create, Clone, Power on, Power off, Suspend, Migrate, and update VM Storage Profile on VVol datastore might fail with a generic error message in task manager that does not indicate whether the issue is with VASA Provider or VMware."
---
= Virtual machine provisioning fails with an undefined error
:icons: font
:imagesdir: ../media/

[.lead]
Virtual machine provisioning operations such as Create, Clone, Power on, Power off, Suspend, Migrate, and update VM Storage Profile on VVol datastore might fail with a generic error message in task manager that does not indicate whether the issue is with VASA Provider or VMware.

== Issue

You receive error messages in task manager such as `No suitable volume was found amongst the candidate volumes for the specified requirements.`

== Cause

The error might occur due to issues with VMware, VASA Provider, or ONTAP storage. The error message might not specify the exact reason for failure. The issue might also be due to large storage systems with a large number of storage virtual machines (SVMs), volumes, and LUNs in the environment. The periodic discovery operations running in the background on such storage systems take time and might cause the timeout of virtual machine provisioning operations if these operations are triggered simultaneously.

== Corrective action

. Verify whether the issue is with VASA Provider or ONTAP storage by examining the `/opt/netapp/vpserver/logs/error.log`, `vvolvp.log`, and `zapi_error.log` log files.
 ** If errors such as `NaException com.netapp.offtap3.ontap.ApiFailedException: No suitable volume was found amongst the candidate volumes for the specified requirements. Details: Vvol Placement: Type: place Candidate Volumes: Vvol_nfs_pb2, Vvol_nfs_pb1 Performance: Greatest IOPS Size: 4GB Space Guaranteed: false Volumes with insufficient unpromised IOPS: Vvol_nfs_pb1, Vvol_nfs_pb2 Result: success (errno=13001)` are reported, then you should take corrective action, such as increasing IOPS on storage with the help of the storage administrator.
 ** You must run provisioning operations only when there is no discovery operation running in the background.
If the errors reported in the VASA Provider log files are not specific, then you should follow up with technical support to resolve the issue.
. If no specific errors are reported in the VASA Provider log files, examine the `sps.log` log file to verify whether the issue is with VMware, and then take suitable corrective action based on the errors reported.
+
If the errors reported in the `sps.log` log file are not specific, then you should follow up with a VMware administrator to resolve the issue.
