---
permalink: manage/task-resize-datastores.html
sidebar: sidebar
keywords: resizing, datastores,
summary: "Resizing a datastore enables you to increase or decrease the storage for your virtual machine files. You might need to change the size of a datastore as your infrastructure requirements change."
---
= Resizing datastores
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
Resizing a datastore enables you to increase or decrease the storage for your virtual machine files. You might need to change the size of a datastore as your infrastructure requirements change.

.Before you begin

If you want VSC to resize the containing volume when it resizes the VMFS datastore, you should not use the *Use existing volume* option under *Storage attributes* section when initially provisioning VMFS datastore, but instead let it automatically create a new volume for each datastore.

.About this task

You can increase or decrease the size of an NFS datastore. You can only increase the size of a VMFS datastore.

.Steps

. From the vSphere Client *Home* page, click *Hosts and Clusters*.
. In the navigation pane, select the datacenter that contains the datastore.
. Right-click the datastore and select menu:NetApp VSC[Resize].
. In the *Resize* dialog box, specify a new size for the datastore, and then click *OK*.
+
You can run the *REDISCOVER ALL* option in the *Storage Systems* menu to manually update the storage listing under Storage Systems and dashboard, or wait for the next scheduled refresh.
