---
permalink: manage/task-setting-default-credentials-for-storage-systems.html
sidebar: sidebar
keywords: 
summary: 'You can use Virtual Storage Console for VMware vSphere to set default credentials for a storage system in your vCenter Server.'
---
= Setting default credentials for storage systems
:icons: font
:imagesdir: ../media/

[.lead]
You can use Virtual Storage Console for VMware vSphere to set default credentials for a storage system in your vCenter Server.

== Before you begin

You must have selected the vCenter Server that you want to use for creating default credentials.

== About this task

If you set up default credentials for storage systems, Virtual Storage Console (VSC) uses these credentials to log in to a storage system that VSC has just discovered. If the default credentials do not work, you must manually log in to the storage system. VSC and SRA support addition of storage system credentials at the cluster level or the SVM level. But VASA Provider will only work with cluster level credentials.

== Steps

. On the VSC *Home* page, click *Settings* > *Administrative Settings* > *Configure Default Credentials for Storage System*.
. In the *Storage System Default Credentials* dialog box, enter the user name and password for the storage system.
+
Storage controller credentials are assigned in ONTAP based on the user name and password pair. The storage controller credentials can either be the administrator account or a custom account that uses role-based access control (RBAC).
+
You cannot use VSC to change the roles that are associated with the user name and password pair of the storage controller. To modify or create a new ONTAP user role for use with the virtual appliance for VSC, VASA Provider, and SRA, you can use System Manager.
+
See the "`Configuring user roles and privileges`" section in the _Virtual Storage Console, VASA Provider, and Storage Replication Adapter for VMware® vSphere Deployment and Setup Guide For 9.7 Release_.

. Click *OK* to save the default credentials.

== After you finish

If you updated the storage system credentials because a storage system reported "`Authentication Failure`" status, you should click the *REDISCOVER ALL* option available on the Storage Systems page. When you do this, VSC tries to connect to the storage system by using the new credentials.
