---
permalink: manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html
sidebar: sidebar
keywords: 
summary: 'You can monitor the performance and view the top five SAN VMware Virtual Volumes \(vVols\) datastores in your vCenter Server based on the parameters that you select by using the vVol dashboard of the virtual appliance for Virtual Storage Console \(VSC\), VASA Provider, and Storage Replication Adapter \(SRA\).'
---
= Monitoring vVols datastores and virtual machines using the vVol dashboard
:icons: font
:imagesdir: ../media/

[.lead]
You can monitor the performance and view the top five SAN VMware Virtual Volumes (vVols) datastores in your vCenter Server based on the parameters that you select by using the vVol dashboard of the virtual appliance for Virtual Storage Console (VSC), VASA Provider, and Storage Replication Adapter (SRA).

== Before you begin

* You should have enabled OnCommand API Services 2.1 or later if you are using ONTAP 9.6 or earlier.
+
You do not require to register OnCommand API Services with VASA Provider to get the details of SAN vVols datastore or SAN vVols VM datastore report for ONTAP 9.7.
+
https://mysupport.netapp.com/site/[NetApp Support]

* You should be using ONTAP 9.3 or later for your storage system.

link:reference_verifying_vvol_dashboard_data_requirements.md#[vVol dashboard data requirements]

== About this task

The IOPS data that is provided by ONTAP is rounded off and displayed on the vVol dashboard. There might be a difference between the actual IOPS value that is provided by ONTAP and the IOPS value that is displayed on the vVol dashboard.

[NOTE]
====

* If you are registering OnCommand API Services for the first time, then you can view all of the performance metrics data for SAN vVols datastores on the vVol dashboard only after 15 to 30 minutes.
* The vVol dashboard data is refreshed periodically, at an interval of 10 minutes.
* If you have added, modified, or deleted a storage system from your vCenter Server instance, then you might not notice any change in the data on the vVols dashboard for some time.
+
This is because OnCommand API Services takes time to obtain updated metrics from ONTAP.

* The Total IOPS value that is displayed in the Overview portlet of the vVol dashboard is not a cumulative value of the Read IOPS value and Write IOPS value.
+
Read IOPS, Write IOPS, and Total IOPS are separate metrics that are provided by OnCommand API Services. If there is a difference between the Total IOPS value and the cumulative IOPS value (Read IOPS value + Write IOPS value) provided by OnCommand API Services, then the same difference is observed in the IOPS values on the vVol dashboard.

====

== Steps

. From the vSphere Client home page, click *Virtual Storage Console*.
. Select the required vCenter Server using the *vCenter server* drop-down menu to view the datastores.
. Click *vVol Dashboard*.
+
The Datastores portlet provides the following details:

 ** The number of vVols datastores that are managed by VASA Provider in your vCenter Server instance
 ** The top five vVols datastores based on resource usage and performance parameters
You can change the listing of the datastores based on the space utilized, IOPS, or latency and in the order required.

. View the details of the virtual machines using the *Virtual Machines* portlet.
+
The Virtual Machines portlet provides the following details:

 ** Number of virtual machines using ONTAP datastores in your vCenter Server
 ** Top five virtual machines based on IOPS, latency, throughput, committed capacity, uptime, and logical space
You can customize how the top five virtual machines are listed in the vVol dashboard.
